version: '3'
services:
  web:
    image: nginx:latest
    links: 
      - api:api
    ports:
      - "3000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  api:
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./api/:/app/
    command: "cargo run" 
