version: '3.8'
services:
  web:
    image: nginx:latest
    depends_on:
      - db
    links: 
      - api:api
    ports:
      - "3000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  api:
    build:
      dockerfile: ./api/Dockerfile
    depends_on:
      - db
    ports:
      - "3030:3030"
    volumes:
      - ./api/:/app/
    command: "cargo run" 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
