//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "thread")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub question_id: Option<Uuid>,
    pub answer_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_one = "super::message::Entity",
        from = "Column::AnswerId",
        to = "super::message::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Message2,
    #[sea_orm(
        has_one = "super::message::Entity",
        from = "Column::QuestionId",
        to = "super::message::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Message1,
}

impl ActiveModelBehavior for ActiveModel {}
