[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.63"
rquest_core = { path = "../core" } 

sea-orm = { version = "^0" }
serde = { workspace = true } 
